Больше деталей
htmlacademy-javascript/1592203-keksobooking-25 pull request #3
Opened 2022-02-26 16:22 UTC by arttiam

---
:mortar_board: [Больше деталей](https://up.htmlacademy.ru/javascript/25/user/1592203/tasks/8)

2022-02-28 01:43 UTC, Espanol-nikkol requested changes

2022-02-28 01:43 UTC, Espanol-nikkol commented on js/main.js
> +const arrayObject = Array.from({length: 10}, createObject);
линтер ругается на объявление без использования

2022-02-28 01:43 UTC, Espanol-nikkol commented on js/main.js
> +  if (numberImages < 10) {
есть встроенные в язык возможности для форматирования таких моментов - метод padStart для строк. Воспользуйся им и упрости это место

2022-02-28 01:43 UTC, Espanol-nikkol commented on js/main.js
> +    author: {avatar: getNumberImages(10)},
тут ты вызываешь функцию, передавая ей число, но в объявлении функции ты не пишешь, что она принимает какие-то параметры

2022-02-28 01:43 UTC, Espanol-nikkol commented on js/main.js
> +const getNumberImages = () => {
получить номер изображений? Получить количество изображений? Если ты пишешь getNumberSmth, то и вернуть надо количество (если ты его имел ввиду) чего-то. А мы возвращаем здесь фоточку, причем не просто фоточку, а конкретно аватарку. Давай изменим имя на более соответствующее

2022-02-28 01:43 UTC, Espanol-nikkol commented on js/main.js
> +const getArrayPhotos = (elements, length) => {
использование множественного числа существительного само по себе говорит о массиве, т.к. много чего-то - это и есть массив. Получается, что мы либо используем getArrayPhoto, либо getPhotos. Какой лучше?

2022-02-28 01:43 UTC, Espanol-nikkol commented on js/main.js
> +  for (let i=0; i < length; i++) {
можешь обойтись без цикла for?
Подумай про сочетание массива с размером length и метода, который бы прошелся по всем элементам этого массива

2022-02-28 01:43 UTC, Espanol-nikkol commented on js/main.js
> +function getRandomArrayElement(elements) {
array - избыточное слово. Ты говоришь, "получить случайный элемент массива", но элементы есть только в массивах, в объектах ключи и значения, в строках символы. Таким образом получается, что "получить случайный элемент" и "получить случайный элемент массива" - равнозначны, но один вариант длиннее.

2022-02-28 01:43 UTC, Espanol-nikkol commented on js/main.js
> +const getArrayFeatures = (elements, length) => {
сам способ придумывал?

2022-02-28 01:43 UTC, Espanol-nikkol commented on js/main.js
> +function createObject() {
очень неопределенное имя. Какой объект? Чего создаем? Давай более конкретно назовем. 
К тому же,обрати внимание, что функция, которая создает объект, его не возвращает. Потому что "создать" - это создать где-то и всё. А мы хотим ведь его получить и использовать

2022-02-28 01:43 UTC, Espanol-nikkol commented on js/main.js
> +const getArrayFeatures = (elements, length) => {
У тебя то классическое определение функции, через ключевое слово, то новое через  const. Надо выбрать одно
https://up.htmlacademy.ru/javascript/25/criteries#d5

2022-02-28 03:38 UTC, arttiam commented on js/main.js
> +const getArrayFeatures = (elements, length) => {
const getArrayFeatures = (elements, length) => { -если это, то да

2022-02-28 03:56 UTC, arttiam commented on js/main.js
> +const arrayObject = Array.from({length: 10}, createObject);
знаю, по заданию ее просто формировать

2022-02-28 06:10 UTC, arttiam commented on js/main.js
> +  for (let i=0; i < length; i++) {
нет, не могу, не получилось

2022-03-01 12:06 UTC, Espanol-nikkol requested changes

2022-03-01 12:06 UTC, Espanol-nikkol commented on js/main.js
> +const arrayObject = Array.from({length: 10}, getCard);
всё ещё не используемая переменная. Просто вызови функцию в пустоте, чтобы линтер не ругался на неиспользуемую функцию. Как это было в прошлой задаче

2022-03-01 12:06 UTC, Espanol-nikkol commented on js/main.js
> +  /*const features = new Array(length).map(() => {
зачем оставил коммент?
Либо убираем, либо используем

2022-03-01 12:06 UTC, Espanol-nikkol commented on js/main.js
> +const arrayObject = Array.from({length: 10}, getCard);
" напишите необходимые функции для создания массива из 10 сгенерированных JS-объектов."
 Напишите функции, но не создавайте собственно массив объявлений

2022-03-01 12:06 UTC, Espanol-nikkol commented on js/main.js
> +function getArrayFeatures(elements, length) {
тоже самое с названием, что и с фотками было. Либо множественное число, либо слово  Array и единственное число

2022-03-01 15:20 UTC, Espanol-nikkol approved these changes

2022-03-01 15:37 UTC, merged